apiVersion: v1
kind: Service
metadata:
  name: devsecops-dashboard-service
spec:
  type: NodePort
  selector:
    app: devsecops-dashboard
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080